#+title: IHPCSS Mentoring Guide
#+author: IHPCSS Mentoring Committee
#+date: October 21, 2022

#+latex_class_options: [titlepage]
#+LATEX_HEADER: \let\oldsection\section
#+LATEX_HEADER: \renewcommand{\section}{\clearpage\oldsection}

* Mentoring Overview
** What is mentoring?

Mentoring is a partnership between two people, the mentor and the mentee, who can share experiences. A mentor can provide guidance, support, and space for the mentee to think as well as helping them progress in their career, overcome work-related issues, and realize their potential. It is a helpful relationship based upon mutual trust and respect.

Mentoring provides a chance for mentees to reflect on themselves, the challenges and opportunities faced, and what they want in life. Mentors will try to help mentees become more self-aware, take responsibility, determine their goals, and help mentees achieve them.  Mentors use their own experience to empathize with the mentee and share wisdom gained.

Mentors should ask questions and challenge their mentees, while providing guidance and encouragement. Mentoring at the summer school does not generally deal with technical problems, but we encourage mentoring on both technical and non-technical issues, including interacting with other staff when useful.

Traditional mentoring partnerships last for a predetermined amount of time, typically two to three years. At the summer school we hope that the brief interaction with your mentor will still provide you with useful insight and hopefully develop into a longer term arrangement if useful.

** How does mentoring work at the summer school?

There are two types of mentors at the summer school: near-peer mentors and staff mentors. Near-peer mentors are returning students who have previously attended the summer school. They understand the stresses of being a graduate student and have some experience with taking the next step. Staff mentors are those individuals who are organizing and presenting at the summer school. They are typically more experienced in their careers.

Each mentor is assigned 3 or 4 mentees. The matching process is done after everyone has completed a mentoring interest survey.  Some students will be assigned a near-peer mentor, and some students a staff mentor. These mentoring groups are assigned based on the responses from the matching surveys. While we do our best to match based on mutual interests, if you find that you and your mentor aren't compatible, please talk with other mentors instead, or raise this with the mentoring team. Our goal is not to force you to stay with the mentor you were assigned to, but rather that you have a positive mentoring experience. Even if you and your assigned mentor are a good match, we encourage you to talk with other staff members for a variety of perspectives and expertise.

At the Summer School, there will be both formal and informal mentoring opportunities. These will include one-on-one meetings, group mentoring sessions, meals, the poster session, and evening activities. Although students have only one assigned mentor, they are encouraged to interact with both near-peers and staff (as well as each other).

The summer school particularly encourages mentoring in the following areas:

- career planning and progression;
- ways to reduce feelings of isolation;
- help with returning after a career break;
- advice about obtaining a work/life balance;
- networking;
- support for coping with personal issues such as health problems, disabilities, or caring responsibilities alongside a professional career;
- development of new skills such as leadership or public speaking.

After the Summer School, the formal mentoring relationship is over. We encourage students and mentors to keep in touch, but it is not required.

* Guide for Mentees
** How does mentoring work at the Summer School?
You and 2-3 other students will be assigned to a mentor as a group, based on the interests you indicated in the mentoring survey.  In advance, please connect with your assigned mentor, though a video call, email or Slack chat.

At the Summer School, there will be both formal mentoring opportunities, as outlined in the schedule, and informal opportunities, such as the poster session, social events.  We hope you take advantage of both to interact with your mentor, other staff, and your fellow students.

We know that connecting with people is not always easy even during in-person events, but your Summer School experience will be enhanced if you're able to get to know the staff and your fellow students.

While we do our best to match based on mutual interests, if you find that you and your mentor aren't compatible, please talk with other mentors instead, or raise this with the mentoring team. Our goal is not to force you to stay with the mentor you were assigned to, but rather that you have a positive mentoring experience. Even if you and your assigned mentor are a good match, we encourage you to talk with other staff members for a variety of perspectives and expertise.

** What can I do to get the most out of mentoring?
Much of this information is taken from an invaluable resource: Adviser, Teacher, Role Model, Friend: On Being a Mentor to Students in Science and Engineering (1997).

In general, an effective mentoring relationship is characterized by mutual respect, trust, understanding, and empathy. Good mentors are able to share life experiences and wisdom, as well as technical expertise. They are good listeners, good observers, and good problem-solvers. They make an effort to know, accept, and respect the goals and interests of a student. In the end, they establish an environment in which the student's accomplishment is limited only by the extent of his or her talent.

** Why should I participate?
- Gain access to a new network of contacts
- Get a broader diversity of perspectives than your own advisor or department
- Learn from someone else's experiences
- Obtain help in achieving your goals
- Improve your self-confidence
** What can I do to get the most out of mentoring?
- Keep in touch with your mentor before, during, and after the Summer School. You may not have burning questions at all times, but reaching out to your mentor will help you establish a good relationship with them.
- Ask your mentor any questions you may have – don't hold back! Even if your mentor doesn't have the answer, he or she can help you find another mentor in our community who can answer your question.
- Feel free to disagree with your mentor, question your mentor, or ask for clarification. They can only assess how helpful they are if you give feedback.
- Your mentor is there to help you to think through your options and help you to formulate your plans. You make the decisions and you take the responsibility.
- Always seek mentoring in a public space.
- Reach out beyond your assigned mentor. Getting a variety of opinions from multiple mentors is a great idea.
- Talk to the mentoring team if you are not happy with your mentoring group.
** What should I avoid?
- Assuming that because technical areas differ, your mentor's advice is not applicable.
- Assuming that your mentor cannot possibly understand your situation. Give them a chance – you might be surprised!
- Assuming your mentoring match will be perfect. No match is perfect and your mentor may only be able to help you with some of your issues; this does not mean that the partnership will not work. Discuss your aims and goals; find out the strengths of your mentor and the areas in which your mentor feels able to assist.
** What should I talk about with my mentor?
You will have many opportunities to talk to your mentor and fellow mentees, and the better prepared you are the more you will benefit from them. You should spend some time thinking what it is that you want to talk with your mentor about.

Things you may want to talk about include:

- How to organize your time and responsibilities
- How to achieve a work-life balance
- Personal and professional challenges – how to make the best out of them
- What to expect from working in the industry/academia/government/etc.
- How to adapt to working in an international setting or another country
- How to find funding
- How to get access to HPC resources
- Different working arrangements – What is it like to work from home/work remotely?
- Professional etiquette
- How to talk to people
- How to effectively build your network
- How to deal with people issues at work (e.g., problems with your advisor, manager, confrontations, etc.)
- How to succeed in a job interview

* Guide for Mentors
** How does mentoring work at the Summer School?
You will be assigned 2-4 students to mentor, based on the interests you indicated in the mentoring survey. Please contact the students in advance of the Summer School, to let them know you're their assigned mentor and to open communication in case they have any questions. This doesn't need to be a video call; just an email or Slack message is fine too. We also recommend to start your first meeting with Ice Breaker Game, which can help to build a relationship between you and your mentees.
At the Summer School, there will be both formal mentoring opportunities, as outlined in the schedule, and informal opportunities, such as the poster session, social events.  We hope you take advantage of both to interact with your mentees. None of the mentoring sessions, social events, or informal interactions will be recorded.

Additionally, please have a chance to speak with each of your mentees during the Summer School, at whatever time is convenient for both of you. The purpose of this meeting is to give your mentee a chance to ask any questions they'd prefer to discuss in private, and give you a chance to check in with them. These don't need to be long discussions, but let your mentee guide it.

While we do our best to match based on mutual interests, if you find that you are not able to adequately help one of your mentees please either talk to the mentoring team or encourage your mentee to. If your mentee(s) choose to approach alternative mentors do not take this personally. We will be encouraging all mentees to talk with other staff members for a variety of perspectives and expertise.

** Principles of Good Mentoring
Much of this information is taken from an invaluable resource: Adviser, Teacher, Role Model, Friend: On Being a Mentor to Students in Science and Engineering (1997).

In general, an effective mentoring relationship is characterized by mutual respect, trust, understanding, and empathy. Good mentors are able to share life experiences and wisdom, as well as technical expertise. They are good listeners, good observers, and good problem-solvers. They make an effort to know, accept, and respect the goals and interests of a student. In the end, they establish an environment in which the student's accomplishment is limited only by the extent of his or her talent.

Mentoring can happen before, during, and after the Summer School. Be ready to practice the following:

- Listen without judgment. IHPCSS students are smart students with their own cultural needs and they will follow their own paths. However, there is no better way to impede their progress than to judge their choices.
- Realize that you will not have all the answers. Take the time to direct students to someone who can help where you may be less able to.
- Keep in touch with your student before and after the Summer School. Make sure you provide opportunities for questions and be aware that they may not feel comfortable initiating discussions. They may not have burning questions at all times, but by making contact you provide opportunities for them to reach out to you.

When working with any student, particularly those from a different background or those with a disability, remember that the student has already learned how to overcome many challenges in their own life. They are the experts on communicating their own abilities, needs, and challenges. If you are having a difficult time communicating, the mentee will surely not take issue if you ask them for help in how to best mentor and communicate with them.

** Benefits of effective mentoring for mentors
- Develop your professional network with up-and-coming scientists.
- Gain feeling of satisfaction from helping a student grow in confidence and achieve goals.
- Stay in touch with new developments and challenges faced by graduate students and post-docs.
- Build your interpersonal skills.
- Reflect upon your own practices.
** Mentoring Tips
*** Things to do
- Ask questions and challenge;
- Suggest networking opportunities;
- Boost confidence and encourage;
- Offer advice but remember that the decision to act on it is the mentee's;
- Nudge, not nag;
- Always behave in a professional manner;
- Always mentor in a public space.
- Try and respond to emails promptly, even if it is just to say that you will be in touch soon. It can be very difficult for some mentees to ask questions, so then delaying in responding, or being dismissive can be extremely detrimental and discourage them from reaching out in the future.
*** Things to avoid
- "Do as I say, not as I do/did"
- Mistaking cultural deference for apathy or understanding.
- Harassing a student for information they are not comfortable giving in order to "help" them. Stick to the natural progression of relationships and let them bring it to you.
- Being distracted when meeting with your mentees: make sure to give the student your full attention by minimizing distractions during the time spent with your mentees.
- Assuming you know best: allow the mentee to explore options and solutions with you - but the choice of solution should be that of the mentee.
